# This file is used to configure the release build step that publishes the
# newly-released package version For the install script and version check
# endpoint.

type = "javascript"
account_id = "b5d1a3835f0dd218f633c7d612935c6b"
route = ""
zone_id = ""

kv_namespaces = [
         { binding = "VERSIONS", id = "4a962eeab391457896db4360bd3f4658", preview_id = "08bbd17bba074685bf9eb875cc46045a" }
]
